# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e246d6b5c83deebf2e427565119a3e4ff82d8d8ccbc540684d568fd790f14d50fbf8e76df47388b72d5a5b4415df8029c52af6641f430a0e7695114c7893678f

test:
  secret_key_base: 17b824110f013e26874fa07c6fec85efeda2485fcfdd97614e641f4541a6c6254858c677dad949535de5d769d1862ae0a6fb405ea361707c806722c31c0dd166

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
